-- grants for app_data
GRANT CREATE SESSION TO app_code;
GRANT CREATE PROCEDURE TO app_code;
GRANT CREATE SYNONYM TO app_code;
GRANT CREATE SESSION TO app_admin;
GRANT CREATE PROCEDURE TO app_admin;
GRANT CREATE SYNONYM TO app_admin;
GRANT CREATE SESSION TO app_user;
GRANT CREATE SYNONYM TO app_user;


